branches:
  except:
    - gh-pages
language: node_js
node_js:
  - "10"
install: npm install
cache: 
  npm: false
jobs:
  include:
    # 代码检查
    - stage: lint
      script: npm run lint
      name: lint
    # 执行测试
    - stage: test
      script: ./script/ci/test.sh
      name: test
    # 编译
    - stage: compile
      script: npm run compile && npm run dist && npm run docs
      name: compile
      deploy:
        - provider: npm
          skip_cleanup: true
          email: xrs4433@outlook.com
          api_token: $NPM_TOKEN
          on:
            tags: true
        - provider: pages
          skip_cleanup: true
          token: $GITHUB_TOKEN
          local_dir: ./docs
          target_branch: gh-pages
          on:
            tags: true
