branches:
  except:
    - gh-pages
sudo: required
language: node_js
node_js:
  - '10'
install: npm install
cache:
  npm: false
jobs:
  include:
    # 代码检查
    - stage: lint
      script: ./script/ci/lint.sh
      name: lint
    # 执行测试
    - stage: test
      script: ./script/ci/test.sh
      name: test
    # 编译
    - stage: compile
      script: ./script/ci/compile.sh
      name: compile
      deploy:
        - provider: npm
          skip_cleanup: true
          email: xrs4433@outlook.com
          api_key: $NPM_TOKEN
          on:
            tags: true
        - provider: pages
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          local_dir: ./docs
          target_branch: gh-pages
          on:
            tags: true
